### ISSUE TITLE
'NoneType' object has no attribute 'RasterCount'

### ISSUE THREAD

**Issue by noureddinebenhalima** [raktim-ghosh/poldecomp#1]
i have problem with image tif , how i can find image tif contain cohrence matrix and covariance matrix

**Comment by raktim-ghosh** [comment]
Image Tif doesn't contain a coherency or covariance matrix. By utilizing the HH, HV, VH, and VV combination of SAR, those matrices are generated.

**Comment by noureddinebenhalima** [comment]
Hi sir .
how i can get this image , i need '' image San Francisco '' , if you have
but we here have four image hh , hv , vh , vv
how can I do four images in one image '' tif ''
 thanks a lot sir
cordially  ...

**Comment by raktim-ghosh** [comment]
You can try layer stacking in Python to merge HH, HV, VH, and VV into one tensor. Before that don't forget to separate the amplitude and phase for all the channels. Therefore, you will have 4 * 2 = 8 different channels.

**Comment by noureddinebenhalima** [comment]
ghh

**Comment by noureddinebenhalima** [comment]
hollo sir
how are you
i have this error or warnings :
'' Warning 1:  TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples''   and this error ''
poldecomp\__init__.py:1850: divide by zero encountered in double_scalars
ps[i, j] = s[i, j] - abs((c[i, j] * np.conj(c[i, j]))) / d[i, j]
poldecomp\__init__.py:1851  RuntimeWarning: divide by zero encountered in log10
  return [10 * np.log10(abs(ps)), 10 * np.log10(abs(pd)),
poldecomp\__init__.py:1852: RuntimeWarning: divide by zero encountered in log10
10 * np.log10(abs(pv)), 10 * np.log10(abs(pc))]
knowing i changed 3 different images
sir ,how can i solve that
